/**
 * Schnorr signature implementation for Lotus
 *
 * This implements the custom Schnorr signature scheme used by Lotus (BCH-derived),
 * which is different from BIP340 (Bitcoin Taproot).
 *
 * Reference: lotusd/src/secp256k1/src/modules/schnorr/schnorr_impl.h
 *
 * Key Differences from BIP340:
 * - Uses compressed public key (33 bytes) instead of x-only (32 bytes)
 * - Hash construction: e = Hash(R.x || compressed(P) || m) instead of Hash(R.x || P.x || m)
 * - Verification equation: R = s*G - e*P (standard Schnorr)
 * - Checks that R.y is a quadratic residue (Jacobi symbol = 1)
 *
 * Signature Format:
 * - 64 bytes total: [R.x (32 bytes) || s (32 bytes)]
 * - No sighash byte appended to raw signature
 *
 * Signing: s = k + e*x where e = Hash(R.x || compressed(P) || m) mod n
 * Verification: Check that s*G - e*P has x-coordinate equal to r and y is quadratic residue
 */

import { BN } from './bn'
import { Point } from './point'
import { Signature } from './signature'
import { Hash } from './hash'
import { PrivateKey } from '../privatekey'
import { PublicKey } from '../publickey'
import { BufferUtil } from '../util'
import type { Buffer } from 'buffer/'

/**
 * Data structure for initializing a Schnorr signature instance
 */
export interface SchnorrData {
  /** 32-byte hash buffer to sign or verify */
  hashbuf?: Buffer
  /** Byte endianness for hash interpretation */
  endian?: 'little' | 'big'
  /** Private key for signing operations */
  privkey?: PrivateKey
  /** Public key for verification */
  pubkey?: PublicKey
  /** Schnorr signature object */
  sig?: Signature
  /** Result of signature verification */
  verified?: boolean
}

export class Schnorr {
  /** 32-byte hash buffer to sign or verify */
  hashbuf!: Buffer
  /** Byte endianness for hash interpretation ('little' or 'big') */
  endian!: 'little' | 'big'
  /** Private key for signing operations */
  privkey!: PrivateKey
  /** Public key for verification (auto-derived from privkey if not set) */
  pubkey!: PublicKey
  /** Schnorr signature object (generated by sign(), verified by verify()) */
  sig!: Signature
  /** Result of signature verification (true if valid, false if invalid) */
  verified!: boolean

  /**
   * Creates a new Schnorr signature instance
   *
   * @param obj - Optional initialization data for the instance
   * @example
   * ```typescript
   * const schnorr = new Schnorr({ hashbuf, privkey })
   * ```
   */
  constructor(obj?: SchnorrData) {
    if (obj) {
      this.set(obj)
    }
  }

  /**
   * Sets instance properties from a data object
   *
   * This method allows chaining by returning 'this'. It intelligently
   * derives the public key from the private key if pubkey is not provided.
   *
   * @param obj - Data object containing properties to set
   * @returns This Schnorr instance for method chaining
   */
  set(obj: SchnorrData): Schnorr {
    this.hashbuf = obj.hashbuf || this.hashbuf
    this.endian = obj.endian || this.endian
    this.privkey = obj.privkey || this.privkey
    this.pubkey =
      obj.pubkey || (this.privkey ? this.privkey.toPublicKey() : this.pubkey)
    this.sig = obj.sig || this.sig
    this.verified = obj.verified || this.verified
    return this
  }

  /**
   * Derive public key from the instance's private key
   *
   * Computes the corresponding public key from the private key using
   * elliptic curve point multiplication: P = d*G where d is private key
   * and G is the generator point.
   *
   * @returns This Schnorr instance for method chaining
   * @throws Error if privkey is not set
   */
  privkey2pubkey(): Schnorr {
    this.pubkey = this.privkey.toPublicKey()
    return this
  }

  /**
   * Get the public key from the instance's private key
   *
   * Convenience method that returns the public key without modifying
   * the instance state.
   *
   * @returns The public key derived from the private key
   * @throws Error if privkey is not set
   */
  toPublicKey(): PublicKey {
    return this.privkey.toPublicKey()
  }

  /**
   * Sign the hash using Schnorr signature algorithm
   *
   * Performs the complete Schnorr signing process:
   * 1. Validates inputs (32-byte hash, valid private key)
   * 2. Converts hash to big number
   * 3. Generates signature components using _findSignature()
   * 4. Creates Signature object with Schnorr flag set
   *
   * @returns This Schnorr instance with the 'sig' property set
   * @throws Error if hashbuf is not 32 bytes or privkey is invalid
   */
  sign(): Schnorr {
    const hashbuf = this.hashbuf
    const privkey = this.privkey
    const d = privkey.bn

    if (!hashbuf || !privkey || !d) {
      throw new Error('invalid parameters')
    }
    if (!BufferUtil.isBuffer(hashbuf) || hashbuf.length !== 32) {
      throw new Error('hashbuf must be a 32 byte buffer')
    }

    // Convert hash to BN with endianness, then pass to _findSignature
    // This matches the original bitcore-lib-xpi implementation
    const e = BN.fromBuffer(hashbuf)
    const obj = this._findSignature(d, e)
    obj.compressed = this.pubkey.compressed
    obj.isSchnorr = true

    this.sig = new Signature(obj)
    return this
  }

  /**
   * Find signature values using Lotus Schnorr algorithm
   *
   * Process:
   * 1. Generate deterministic nonce k using RFC6979 with "Schnorr+SHA256  " seed
   * 2. Compute R = k*G
   * 3. If R.y is not a quadratic residue, use n-k instead (negate)
   * 4. Compute e = Hash(R.x || compressed(P) || m) mod n
   * 5. Compute s = k + e*d mod n
   * 6. Return signature (r=R.x, s)
   */
  _findSignature(
    d: BN,
    e: BN,
  ): { r: BN; s: BN; compressed?: boolean; isSchnorr?: boolean } {
    const n = Point.getN()
    const G = Point.getG()

    if (d.lte(BN.Zero)) {
      throw new Error('privkey out of field of curve')
    }
    if (d.gte(n)) {
      throw new Error('privkey out of field of curve')
    }

    let k = this.nonceFunctionRFC6979(
      d.toBuffer({ size: 32 }),
      e.toBuffer({ size: 32 }),
    )

    const P = G.mul(d)
    const R = G.mul(k)

    // Negate k if R.y is not a quadratic residue (Jacobi symbol != 1)
    // This ensures R.y is always a quadratic residue in the final signature
    // CRITICAL: Only negate k, NOT R!
    // Point negation: (-k)*G has the SAME x-coordinate as k*G but opposite y
    if (R.hasSquare()) {
      // k is already correct - R.y is a quadratic residue (even)
    } else {
      // Negate k: use n-k instead
      // This makes the signature use -R which has even y-coordinate
      k = n.sub(k)
    }

    const r = R.x
    const rBuffer = this.getrBuffer(r)

    // Compute e = Hash(R.x || compressed(P) || m) mod n
    // This is the Lotus/BCH Schnorr hash construction
    // Note: compressed(P) is 33 bytes, not x-only like BIP340
    const e0 = BN.fromBuffer(
      Hash.sha256(
        BufferUtil.concat([
          rBuffer,
          Point.pointToCompressed(P),
          e.toBuffer({ size: 32 }),
        ]),
      ),
    )

    const s = e0.mul(d).add(k).mod(n)

    return { r, s, compressed: this.pubkey.compressed, isSchnorr: true }
  }

  /**
   * Ensure r part of signature is at least 32 bytes
   *
   * The BN type naturally cuts off leading zeros, e.g.
   * <BN: 4f92d8094f710bc11b93935ac157730dda26c5c2a856650dbd8ebcd730d2d4> 31 bytes
   * Buffer <00 4f 92 d8 09 4f 71 0b c1 1b 93 93 5a c1 57 73 0d da 26 c5 c2 a8 56 65 0d bd 8e bc d7 30 d2 d4> 32 bytes
   * Both types are equal, however Schnorr signatures must be a minimum of 64 bytes.
   * This ensures the r component is always 32 bytes for proper signature formatting.
   *
   * @param r - The r value as BN
   * @returns Buffer representation (at least 32 bytes, big-endian)
   */
  private getrBuffer(r: BN): Buffer {
    const buf = r.toBuffer()
    return buf.length < 32 ? r.toBuffer({ size: 32 }) : buf
  }

  /**
   * Ensure s part of signature is at least 32 bytes
   *
   * The BN type naturally cuts off leading zeros, e.g.
   * <BN: 4f92d8094f710bc11b93935ac157730dda26c5c2a856650dbd8ebcd730d2d4> 31 bytes
   * Buffer <00 4f 92 d8 09 4f 71 0b c1 1b 93 93 5a c1 57 73 0d da 26 c5 c2 a8 56 65 0d bd 8e bc d7 30 d2 d4> 32 bytes
   * Both types are equal, however Schnorr signatures must be a minimum of 64 bytes.
   * This ensures the s component is always 32 bytes for proper signature formatting.
   *
   * @param s - The s value as BN
   * @returns Buffer representation (at least 32 bytes, big-endian)
   */
  private getsBuffer(s: BN): Buffer {
    const buf = s.toBuffer()
    return buf.length < 32 ? s.toBuffer({ size: 32 }) : buf
  }

  /**
   * Check for signature errors (verification)
   *
   * Lotus Schnorr Verification:
   * 1. Check signature length is 64 or 65 bytes (65 with sighash byte)
   * 2. Check r < p (field prime) and s < n (curve order)
   * 3. Compute e = Hash(r || compressed(P) || m) mod n
   * 4. Compute R = s*G - e*P
   * 5. Check R is not infinity
   * 6. Check R.y is a quadratic residue
   * 7. Check R.x == r
   *
   * @returns True if verification fails (signature is invalid), false if signature is valid
   */
  sigError(): boolean {
    if (!BufferUtil.isBuffer(this.hashbuf) || this.hashbuf.length !== 32) {
      return true
    }

    const hashbuf =
      this.endian === 'little' ? this.reverseBuffer(this.hashbuf) : this.hashbuf
    const P = this.pubkey.point
    const G = Point.getG()

    if (P.isInfinity()) {
      return true
    }

    const r = this.sig.r
    const s = this.sig.s

    const p = BN.fromString(
      'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F',
      'hex',
    )
    const n = Point.getN()

    if (r.gte(p) || s.gte(n)) {
      return true
    }

    const Br = this.getrBuffer(this.sig.r)
    const Bp = Point.pointToCompressed(P)

    // Compute challenge: e = Hash(r || compressed(P) || m) mod n
    const hash = Hash.sha256(BufferUtil.concat([Br, Bp, hashbuf]))
    const e = BN.fromBuffer(hash).mod(n)

    // Verification equation: R = s*G - e*P
    // We compute this as s*G + (-e)*P = s*G + (n-e)*P
    const sG = G.mul(s)
    const eP = P.mul(n.sub(e)) // -e*P = (n-e)*P in modular arithmetic
    const R = sG.add(eP)

    // Check validity conditions:
    // 1. R must not be point at infinity
    // 2. R.y must be a quadratic residue (Jacobi symbol = 1)
    // 3. R.x must equal r (the signature's r value)
    if (R.isInfinity() || !R.hasSquare() || !R.x.eq(r)) {
      return true // Verification failed
    }

    return false
  }

  /**
   * Verify signature
   *
   * Performs Schnorr signature verification and stores the result
   * in the 'verified' property. Uses sigError() internally.
   *
   * @returns This Schnorr instance with 'verified' property set to the verification result
   * @example
   * ```typescript
   * const isValid = schnorr.set({ hashbuf, sig, pubkey }).verify().verified
   * ```
   */
  verify(): Schnorr {
    this.verified = this.sigError() === false
    return this
  }

  /**
   * RFC6979 deterministic nonce generation for Lotus Schnorr
   *
   * Uses HMAC-DRBG with SHA256 and Schnorr-specific domain separator.
   *
   * Key difference from standard RFC6979:
   * - Uses "Schnorr+SHA256  " (with trailing spaces) as the algorithm identifier
   * - This ensures different nonces than ECDSA for the same key and message
   *
   * Reference: lotusd/src/secp256k1/src/modules/schnorr/schnorr_impl.h
   */
  nonceFunctionRFC6979(privkey: Buffer, msgbuf: Buffer): BN {
    let V = BufferUtil.from(
      '0101010101010101010101010101010101010101010101010101010101010101',
      'hex',
    )
    let K = BufferUtil.from(
      '0000000000000000000000000000000000000000000000000000000000000000',
      'hex',
    )

    // Construct the RFC6979 input blob for Schnorr nonce generation
    // Reference: lotusd/src/secp256k1/src/modules/schnorr/schnorr_impl.h
    //
    // The blob consists of:
    // 1. Private key (32 bytes)
    // 2. Message hash (32 bytes)
    // 3. Optional additional data (empty here)
    // 4. Algorithm identifier "Schnorr+SHA256  " (16 bytes with trailing spaces)
    //
    // This domain separator ensures Schnorr signatures use different nonces
    // than ECDSA signatures for the same key and message, preventing nonce reuse attacks.
    const blob = BufferUtil.concat([
      privkey,
      msgbuf,
      BufferUtil.from('', 'ascii'), // 32 bytes if not empty
      BufferUtil.from('Schnorr+SHA256  ', 'ascii'),
    ])

    K = Hash.sha256hmac(
      BufferUtil.concat([V, BufferUtil.from('00', 'hex'), blob]),
      K,
    )
    V = Hash.sha256hmac(V, K)

    K = Hash.sha256hmac(
      BufferUtil.concat([V, BufferUtil.from('01', 'hex'), blob]),
      K,
    )
    V = Hash.sha256hmac(V, K)

    let k = BN.Zero
    let T: BN

    while (true) {
      V = Hash.sha256hmac(V, K)
      T = BN.fromBuffer(V)

      k = T
      if (V.length < 32) {
        throw new Error('V length should be >= 32')
      }
      if (k.gt(BN.Zero) && k.lt(Point.getN())) {
        break
      }
      K = Hash.sha256hmac(
        BufferUtil.concat([V, BufferUtil.from('00', 'hex')]),
        K,
      )
      V = Hash.sha256hmac(V, K)
    }

    return k
  }

  /**
   * Static sign method
   *
   * @param hashbuf - 32-byte hash buffer to sign
   * @param privkey - Private key for signing
   * @param endian - Byte endianness ('little' or 'big')
   * @returns Schnorr signature
   */
  static sign(
    hashbuf: Buffer,
    privkey: PrivateKey,
    endian?: 'little' | 'big',
  ): Signature {
    return new Schnorr()
      .set({
        hashbuf: hashbuf,
        endian: endian,
        privkey: privkey,
      })
      .sign().sig
  }

  /**
   * Static verify method
   *
   * @param hashbuf - 32-byte hash buffer that was signed
   * @param sig - Signature to verify
   * @param pubkey - Public key to verify against
   * @param endian - Byte endianness ('little' or 'big')
   * @returns True if signature is valid, false otherwise
   */
  static verify(
    hashbuf: Buffer,
    sig: Signature,
    pubkey: PublicKey,
    endian?: 'little' | 'big',
  ): boolean {
    return new Schnorr()
      .set({
        hashbuf: hashbuf,
        endian: endian,
        sig: sig,
        pubkey: pubkey,
      })
      .verify().verified
  }

  /**
   * Reverse buffer byte order
   *
   * Used for converting between little-endian and big-endian representations
   * of hash values. This is needed when interpreting hashes with different
   * endianness conventions.
   *
   * @param buf - Buffer to reverse
   * @returns New buffer with bytes in reversed order
   * @private
   */
  private reverseBuffer(buf: Buffer): Buffer {
    const buf2 = BufferUtil.alloc(buf.length)
    for (let i = 0; i < buf.length; i++) {
      buf2[i] = buf[buf.length - 1 - i]
    }
    return buf2
  }
}
